### ISSUE TITLE
Question: Do we really need to have a Fortran compiler to build/configure this?

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/ISO_Fortran_binding#11]
There are no Fortran sources, so I'm wondering if we really need to have: 
`project(ISO_Fortran_binding <version> languages Fortran C)`.

Couldn't we just have C?

Are we doing any compiler introspection somewhere for the Fortran compiler that I am missing?

Cheers

**Comment by rouson** [comment]
Fortran can be deleted for now.  In the long run, I think it would be nice to have some tests wherein entities are declared in Fortran and then manipulated in C using the functions and data structures in this library, but there are no plans to write such tests anytime soon so feel free to just go with C.
