### ISSUE TITLE
Add a GPL license

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/ISO_Fortran_binding#12]
To Do
------
   - [ ] Research multi-license distribution.
   - [ ] Add the GPL license.
   - [x] Create a Contributor License Agreement.
   - [ ] Ensure that all contributors submit their acknowledgment/acceptance of the new CLA.

**Comment by zbeekman** [comment]
Does GCC/GFortran care about which CLA we use? Do you know which they use? If it's reasonable (or the Linux foundation CLA that we use for OpenCoarrays) we should use theirs.

**Comment by rouson** [comment]
I've added the link to the CLA in the README.md and emailed the other contributors to request CLA signatures.   For now, I'm marking this as wontfix and closing it.  I'll reopen it if we decide to pursue multi-license distribution.
