### ISSUE TITLE
Defect: GCC C extensions used in multiple locations

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/ISO_Fortran_binding#5]
This issue replaces [OpenCoarrays issue 549].

# Defect/Bug Report #

## Observed Behavior ##

- A struct in libcaf_mpi has a variable length member component that is not the last element in the struct: This causes warnings when compiling with clang because it is a GCC C extension
- ISO_Fortran_binding.h uses variable length arrays (VLAs) inside structs which is a GCC C extension

See also discussion on [homebrew pull request 28534].

## Expected Behavior ##

Be able to compile all components written in C because the C code is standards conforming

## Steps to Reproduce ##

compile using clang instead of gcc

## Discussion

1. Is there no option other than enumerating every possible rank?
2. Could this be done with a macro?
3. Could we point from within the struct to an external VLA?

[links]:#
[OpenCoarrays issue 549]: https://github.com/sourceryinstitute/OpenCoarrays/issues/549
[homebrew pull request 28534]:  https://github.com/Homebrew/homebrew-core/pull/28534

**Comment by zbeekman** [comment]
I think we have GNU extensions in the core library too, so I’m reopening.

**Comment by zbeekman** [comment]
Wrong repository... sorry. I'll take this for a test drive with clang.
